"""
容错保障模块
"""
from .fault_tolerance import (
    AppException,
    BusinessError,
    ValidationError,
    AuthenticationError,
    AuthorizationError,
    NotFoundError,
    RateLimitError,
    ExternalServiceError,
    DatabaseError,
    TimeoutError,
    ExceptionHandler,
    exception_handler,
    HealthChecker,
    health_checker,
    GracefulShutdown,
    ExceptionMiddleware,
    retry,
    fallback,
    init_fault_tolerance,
    get_health_status
)

__all__ = [
    "AppException",
    "BusinessError",
    "ValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
    "RateLimitError",
    "ExternalServiceError",
    "DatabaseError",
    "TimeoutError",
    "ExceptionHandler",
    "exception_handler",
    "HealthChecker",
    "health_checker",
    "GracefulShutdown",
    "ExceptionMiddleware",
    "retry",
    "fallback",
    "init_fault_tolerance",
    "get_health_status"
]
